package com.dgf;

import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;

public class JokeService {
    private static final HashMap<String, List<String>> jokesByCategory = new HashMap<>();
    private static final Random random = new Random();

    static {
        // Tech Jokes
        List<String> techJokes = new ArrayList<>();
        techJokes.add("Why do programmers prefer dark mode? Because light attracts bugs.");
        techJokes.add("Why was the JavaScript developer sad? Because he didn't Node how to Express himself.");
        techJokes.add("How many programmers does it take to change a light bulb? None, that's a hardware problem.");
        techJokes.add("Why do Java developers wear glasses? Because they can't C#.");
        techJokes.add("I would tell you a UDP joke, but you might not get it.");
        techJokes.add("An SQL query goes into a bar, walks up to two tables, and asks, 'Can I join you?'");
        techJokes.add("Why do programmers hate nature? It has too many bugs.");
        techJokes.add("Why was the computer cold? It left its Windows open.");
        techJokes.add("Why was the developer unhappy at their job? They wanted arrays.");
        techJokes.add("How do you comfort a JavaScript bug? You console it.");
        techJokes.add("Why was the mobile phone wearing glasses? Because it lost its contacts.");
        techJokes.add("What was the spider doing on the computer? He was making a web-site!");
        techJokes.add("What do you call an iPhone that sleeps too much? Dead Siri-ous.");
        techJokes.add("What did the computer have during his break time? He had a byte!");
        techJokes.add("What is the computer's favorite snack to eat? Microchips!");
        techJokes.add("What shoes do computers love the most? Re-boots!");
        techJokes.add("Why did the computer go to the dentist? To get his Bluetooth checked.");
        techJokes.add("What is the biggest lie anyone can tell? 'I have read and agreed to all the terms and conditions.'");
        techJokes.add("What kind of computer sings the best? A Dell.");
        techJokes.add("Why did the developer become so poor? Because he cleared his cache.");
        techJokes.add("What made the Java developers wear glasses? They can't C.");
        techJokes.add("Knock knock. Who’s there? Hello world! Hello world, who? NameError: name ‘who’ is not defined");
        techJokes.add("How many programmers does it take to change a light bulb? None, because it is a hardware problem.");
        techJokes.add("Why do they call it hyper text? Too much JAVA.");
        techJokes.add("Have you heard of that new band '1023 Megabytes'? They're pretty good, but they don't have a gig just yet.");
        techJokes.add("How did Microsoft Office get so famous? Due to good Word of mouth.");
        techJokes.add("A truck carrying Microsoft software has just overturned on the main road… That's the Word on the street.");
        techJokes.add("Why are Microsoft employees never relaxed? Because they’re always on Edge.");
        techJokes.add("I took a Microsoft Office class in high school… I Excelled in it.");
        techJokes.add("What kind of books grow on trees? Apple MacBooks.");
        techJokes.add("What is a Linux user's favorite game? sudo ku.");
        techJokes.add("Why do vampire's use Linux? Because they don't like Windows in their house.");
        jokesByCategory.put("tech", techJokes);

        // General Jokes
        List<String> generalJokes = new ArrayList<>();
        generalJokes.add("I told my wife she was drawing her eyebrows too high. She looked surprised.");
        generalJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        generalJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field.");
        generalJokes.add("I used to play piano by ear, but now I use my hands.");
        generalJokes.add("What's orange and sounds like a parrot? A carrot.");
        generalJokes.add("Parallel lines have so much in common. It's a shame they'll never meet.");
        generalJokes.add("Did you hear about the kidnapping at the playground? They woke up.");
        generalJokes.add("What do you call a bear with no teeth? A gummy bear.");
        generalJokes.add("How do you organize a space party? You 'planet.'");
        generalJokes.add("I'm reading a book on anti-gravity. It's impossible to put down.");
        generalJokes.add("Why don't scientists trust atoms? Because they make up everything.");
        generalJokes.add("What's brown and sticky? A stick.");
        generalJokes.add("Want to hear a construction joke? Sorry, I'm still building up to it.");
        generalJokes.add("Why don't skeletons fight each other? They don't have the guts.");
        generalJokes.add("Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.");
        generalJokes.add("What do you call a fish with no eyes? Fsh.");
        generalJokes.add("How do you catch a squirrel? Climb a tree and act like a nut!");
        generalJokes.add("Why did the bicycle fall over? Because it was two-tired.");
        generalJokes.add("I told my wife she was drawing her eyebrows too high. She looked surprised.");
        generalJokes.add("Why did the math book look sad? Because it had too many problems.");
        generalJokes.add("How do you organize a space party? You 'planet.'");
        generalJokes.add("What's orange and sounds like a parrot? A carrot.");
        generalJokes.add("I told my wife she was drawing her eyebrows too high. She looked surprised.");
        generalJokes.add("Why did the math book look sad? Because it had too many problems.");
        generalJokes.add("How do you organize a space party? You 'planet.'");
        generalJokes.add("What's orange and sounds like a parrot? A carrot.");
        generalJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field.");
        generalJokes.add("I used to play piano by ear, but now I use my hands.");
        generalJokes.add("What's brown and sticky? A stick.");
        generalJokes.add("Parallel lines have so much in common. It's a shame they'll never meet.");
        generalJokes.add("Did you hear about the kidnapping at the playground? They woke up.");
        generalJokes.add("What do you call a bear with no teeth? A gummy bear.");
        generalJokes.add("How do you organize a space party? You 'planet.'");
        generalJokes.add("I'm reading a book on anti-gravity. It's impossible to put down.");
        generalJokes.add("Why don't scientists trust atoms? Because they make up everything.");
        generalJokes.add("What's brown and sticky? A stick.");
        generalJokes.add("Want to hear a construction joke? Sorry, I'm still building up to it.");
        generalJokes.add("Why don't skeletons fight each other? They don't have the guts.");
        generalJokes.add("Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.");
        generalJokes.add("What do you call a fish with no eyes? Fsh.");
        generalJokes.add("How do you catch a squirrel? Climb a tree and act like a nut!");
        generalJokes.add("Why did the bicycle fall over? Because it was two-tired.");
        generalJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field.");
        generalJokes.add("I used to play piano by ear, but now I use my hands.");
        generalJokes.add("What's orange and sounds like a parrot? A carrot.");
        generalJokes.add("I'm reading a book on anti-gravity. It's impossible to put down.");
        generalJokes.add("Why don't scientists trust atoms? Because they make up everything.");
        generalJokes.add("Want to hear a construction joke? Sorry, I'm still building up to it.");
        generalJokes.add("Why don't skeletons fight each other? They don't have the guts.");
        generalJokes.add("Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.");
        generalJokes.add("What do you call a fish with no eyes? Fsh.");
        generalJokes.add("How do you catch a squirrel? Climb a tree and act like a nut!");
        generalJokes.add("Why did the bicycle fall over? Because it was two-tired.");
        generalJokes.add("What's brown and sticky? A stick.");
        generalJokes.add("Why don't scientists trust atoms? Because they make up everything.");
        generalJokes.add("Parallel lines have so much in common. It's a shame they'll never meet.");
        generalJokes.add("I'm reading a book on anti-gravity. It's impossible to put down.");
        generalJokes.add("Why don't skeletons fight each other? They don't have the guts.");
        generalJokes.add("What do you call a fish with no eyes? Fsh.");
        generalJokes.add("How do you catch a squirrel? Climb a tree and act like a nut!");
        generalJokes.add("Why did the bicycle fall over? Because it was two-tired.");
        jokesByCategory.put("general", generalJokes);

        // 40k Jokes
        List<String> warhammer40kJokes = new ArrayList<>();
        warhammer40kJokes.add("Why did the Chaos Gods stop inviting Khorne to breakfast? Khorne flakes.");
        warhammer40kJokes.add("Who is the most helpful Primarch? Dorn’s always willing to lend a hand.");
        warhammer40kJokes.add("What unit makes the best cashiers? Lords of Change.");
        warhammer40kJokes.add("How do Astartes chefs add flavor? A salt cannon.");
        warhammer40kJokes.add("Who are the best dancers? Khorne Bertwerkers.");
        warhammer40kJokes.add("What vehicle has the most right-wing machine spirit? The Rhino.");
        warhammer40kJokes.add("What do you call it when an Australian Tactical Squad splits into two? Wombat Squading.");
        warhammer40kJokes.add("Why is Magnus so far in college debt? He has a thousand sons.");
        warhammer40kJokes.add("What do people say who hate Autocannons? I Hades Autocannons.");
        warhammer40kJokes.add("Who are the biggest threat to Imperium teeth? Plaque Marines.");
        warhammer40kJokes.add("What are Space Wolf bits called? Kibbles and Bits.");
        warhammer40kJokes.add("Knock Knock. Who’s there? The Inquisition… Knock Knock… Knock Knock [people seen fleeing in background] Knock Knock.");
        warhammer40kJokes.add("What Chapter makes the worst proctologists? Iron Hands.");
        warhammer40kJokes.add("What is the Dark Angels’ favorite restaurant? Buffalo Raven Wings.");
        warhammer40kJokes.add("What race is always crying? Tear-anids.");
        warhammer40kJokes.add("What unit has the worst batting record in baseball? Striking Scorpions.");
        warhammer40kJokes.add("What is the funniest Astartes Chapter? Ultramarines. Because they’re a joke.");
        warhammer40kJokes.add("How many inquisitors does it take to screw in a lightbulb? Three, one to screw it in, one to outlaw lightbulbs and one to deny lightbulbs ever existed.");
        warhammer40kJokes.add("How many space marines does it take to screw in a lightbulb? One hundred, one to screw it in and ninety-nine to praise the emperor.");
        warhammer40kJokes.add("How many Imperial guard does it take to screw in a lightbulb? None, their lasguns will do just fine.");
        jokesByCategory.put("40k", warhammer40kJokes);

        // Halo Jokes
        List<String> haloJokes = new ArrayList<>();
        haloJokes.add("Why'd the SPARTAN cross the road? To get to the other Hog.");
        haloJokes.add("What's a kamikaze grunt's favorite song? I'm Blue. Daba dee daba die.");
        haloJokes.add("How should one greet a forerunner? Wave and say 'Halo'.");
        haloJokes.add("What do you get when you stick a grunt with a brute? You get the brute.");
        haloJokes.add("What's the Master Chief's least favorite natural disaster? Floods.");
        haloJokes.add("Why did Truth lead The Covenant through the Great Journey? He thought that he'd 'Prophet' from it.");
        haloJokes.add("Thel Vadamee bit a cucumber. He immediately spat it out and said: These fruits 'Arbiter'.");
        haloJokes.add("How come Chief's not afraid to die? He knows he'll respawn at the last checkpoint.");
        haloJokes.add("Knock Knock. Who's there? ONI. ONI who? If ONI there were better Halo jokes...");
        haloJokes.add("Why did Jesus lose his Halo? Nobody wanted to play on his team any longer after he had a 0 and 2 kill/death ratio and it took him 3 days to respawn.");
        haloJokes.add("If Gravemind from Halo did product placement... We exist / Together now. Two corpses / In one grave. Burma-Shave.");
        haloJokes.add("I don't understand why anyone would play past the first Halo game. Once you've played the first game, you've seen The Maw.");
        haloJokes.add("In heaven Mother Theresa is complaining to god that Princes Diana's halo is bigger than hers... God giggles... That's not a halo, that's a steering wheel.");
        haloJokes.add("What hymn did the snarky gamer suggest for Sunday mass? The Halo: Combat Evolved theme song. Everyone rejoiced.");
        haloJokes.add("What do you get when a Petty officer from Halo has got some mad cooking skills? Masterchef.");
        haloJokes.add("Bungie is now working on food products based on their own classic games Known as Halo tea bags.");
        haloJokes.add("What does the Sun say a lot? Halo to you.");
        haloJokes.add("A sky high Ground Pound in Halo 5 Should be a medal called 'From the Top Rope!'");
        haloJokes.add("Why did Jesus lose his Halo? Nobody wanted to play on his team any longer after he had a 0 and 2 kill/death ratio and it took him 3 days to respawn.");
        haloJokes.add("If Gravemind from Halo did product placement... We exist / Together now. Two corpses / In one grave. Burma-Shave.");
        haloJokes.add("What do you call a religious door-to-door salesman? A zeal-ot. (bonus points if this made you think of the Halo games)");
        haloJokes.add("Microsoft has realized that all their products get better PR by naming it after Halo mythology. I'm expecting the next Windows version to be Windows 117.");
        haloJokes.add("What did the big angel say to the little angel on Christmas Eve? Answer: \"Halo there!\" What has two wings and a halo? A Japanese phone, Wing wing, \"Halo?\"");
        haloJokes.add("What has two wings and a halo? A Chinese telephone. Wing-Wing. Halo.");
        haloJokes.add("Why didn't Bungie stick with Halo? Because it wasn't their Destiny.");
        haloJokes.add("what is an angel's favorite video game? halo");
        haloJokes.add("What's bigger than Infinity? Halo");
        haloJokes.add("How much does Halo cost? six million jews");
        haloJokes.add("How do gamers greet each other? \"Halo\"");
        haloJokes.add("What's Lionel Richie's favorite video game? Halo.");
        haloJokes.add("When you insult Chuck Norris, the next thing you are going to see is a bunch of halos.");
        haloJokes.add("What does the Sun say a lot? Halo to you.");
        jokesByCategory.put("halo", haloJokes);

        // Star Wars Jokes
        List<String> starWarsJokes = new ArrayList<>();
        starWarsJokes.add("Why did Yoda cross the road? To get to the Dark Side.");
        starWarsJokes.add("What do you call a Wookiee who loves to repair things? Chewbacca the Fixer.");
        starWarsJokes.add("Why did Anakin Skywalker become an archaeologist? He was good at finding artifacts.");
        starWarsJokes.add("How does Darth Vader like his toast? On the dark side.");
        starWarsJokes.add("What do you call a Sith who won't fight? A Sithy cat.");
        starWarsJokes.add("Why don't Stormtroopers play hide and seek? Because good luck hiding in that armor.");
        starWarsJokes.add("What's a Jedi's favorite candy? Obi-Wan Kandycorni.");
        starWarsJokes.add("Why did Kylo Ren bring a ladder to the Millennium Falcon? Because he wanted to join the dark side.");
        starWarsJokes.add("What do you call a smuggler with a cold? Han Sneeze-o.");
        starWarsJokes.add("Why did the Ewok bring a suitcase to the battle? Because he wanted to pack a punch.");
        starWarsJokes.add("What did Darth Vader say when he walked into a vegetarian restaurant? 'I find your lack of steak disturbing.'");
        starWarsJokes.add("Why did Luke Skywalker use the Force to fix his computer? Because it had too many cookies.");
        starWarsJokes.add("What's a Jedi's favorite dessert? Obi-Wan Cannoli.");
        starWarsJokes.add("Why did the droid go to therapy? Because it had too many repressed feelings.");
        starWarsJokes.add("What do you call a group of musical Stormtroopers? An Imperial Marching Band.");
        starWarsJokes.add("Why did Princess Leia become a baker? She had a bun in the oven.");
        starWarsJokes.add("What did Obi-Wan say to Anakin at the bakery? 'You were the chosen bun!'");
        starWarsJokes.add("Why don't Jedi ever eat fast food? Because they prefer the 'light' side.");
        starWarsJokes.add("What's a Jedi's favorite type of car? A Toyoda.");
        starWarsJokes.add("Why did R2-D2 cross the road? To rescue the droid chicken.");
        starWarsJokes.add("What do you call a bounty hunter who loves coffee? Java Fett.");
        starWarsJokes.add("Why did Darth Vader go to therapy? He had too many 'forceful' issues.");
        starWarsJokes.add("What's the Emperor's favorite type of music? Sith-hop.");
        starWarsJokes.add("What do you call a Sith who loves to garden? Darth Maul-kale.");
        starWarsJokes.add("Why did Yoda bring a ladder to the Dagobah swamp? He wanted to reach the high ground.");
        starWarsJokes.add("What's Chewbacca's favorite instrument? The Wookiee-ler.");
        starWarsJokes.add("Why did Luke Skywalker become a musician? Because he had a lot of 'saber' rattling.");
        starWarsJokes.add("What do you call a droid with a sweet tooth? C-3P-Yum.");
        starWarsJokes.add("Why did the Millennium Falcon apply for a loan? It wanted to make some 'credit' alterations.");
        starWarsJokes.add("What do you call a group of Rebel pilots at a concert? The X-Wing Band.");
        starWarsJokes.add("Why did R2-D2 go to therapy? To work on his beepression.");
        starWarsJokes.add("What do you call a bounty hunter from Alderaan? An Alderaanian.");
        starWarsJokes.add("Why was the Death Star so bad at basketball? It always missed its shots.");
        starWarsJokes.add("How does Darth Vader like his coffee? On the dark side with a little force.");
        starWarsJokes.add("Why did Obi-Wan Kenobi invite Darth Maul to a barbecue? He wanted to have a Sith-kebab.");
        starWarsJokes.add("What do you call a Sith who's good at math? Darth Calculus.");
        starWarsJokes.add("Why did the Star Destroyer apply for a job? It wanted to become a Shooting Star.");
        starWarsJokes.add("How do you organize a space party? You 'planet' in advance.");
        starWarsJokes.add("Why did the Millennium Falcon apply for a loan? It needed more 'credit' to make the Kessel Run.");
        starWarsJokes.add("What do you call a group of singing Wookiees? A Chewbaccapella.");
        starWarsJokes.add("Why did Yoda become a gardener? Because he had a green thumb, he did.");
        starWarsJokes.add("How do you get a Wookiee to clean your ship? Use a Chew-bacca vacuum cleaner.");
        starWarsJokes.add("What's Jabba the Hutt's favorite type of music? Heavy metal.");
        starWarsJokes.add("Why did the droid bring a ladder to the bar? Because it heard the drinks were on the house.");
        starWarsJokes.add("What's a Jedi's favorite fruit? Obi-Wan Kenanana.");
        jokesByCategory.put("StarWars", starWarsJokes);

        //Baldurs gate
        List<String> baldursGateJokes = new ArrayList<>();
        baldursGateJokes.add("Why did the adventurer open a bakery in Baldur's Gate? Because they wanted to roll for dough!");
        baldursGateJokes.add("How do you make a mage in Baldur's Gate laugh? Cast \"Tasha's Hideous Laughter\" on them!");
        baldursGateJokes.add("Why did the rogue in Baldur's Gate become a locksmith? Because they were already skilled at picking locks!");
        baldursGateJokes.add("What do you call a group of adventurers in Baldur's Gate who can't agree on a quest? A \"disorganized party\"!");
        baldursGateJokes.add("Why did the bard in Baldur's Gate start a band? Because they wanted to \"charm\" the audience with their music!");
        baldursGateJokes.add("How do you know you're in Baldur's Gate? When even the cows have their own unique side quests!");
        baldursGateJokes.add("Why do adventurers in Baldur's Gate make terrible detectives? Because they always miss the \"clues\"!");
        baldursGateJokes.add("What's a bard's favorite spell in Baldur's Gate? \"Cure Woundsday\"!");
        baldursGateJokes.add("Why did the ranger in Baldur's Gate bring a pet bear to the tavern? Because they wanted to \"paws\" for a drink!");
        baldursGateJokes.add("How do you defeat a mind flayer in Baldur's Gate? With \"psychic\"-kinesis!");
        baldursGateJokes.add("Why did the wizard in Baldur's Gate refuse to leave their tower? Because they were too \"spell\"-bound!");
        baldursGateJokes.add("What's a cleric's favorite dance in Baldur's Gate? \"Turn Undead in Circles\"!");
        baldursGateJokes.add("Why did the paladin in Baldur's Gate become a lawyer? Because they believed in \"divine justice\"!");
        baldursGateJokes.add("How do you know you're in Baldur's Gate? When the local thieves' guild offers guided tours!");
        baldursGateJokes.add("Why did the druid in Baldur's Gate get a job at the zoo? Because they could \"shape-shift\" into any animal on the payroll!");
        baldursGateJokes.add("What's a ranger's favorite drink in Baldur's Gate? \"Wild Berry Wine\"!");
        baldursGateJokes.add("Why did the sorcerer in Baldur's Gate become a stand-up comedian? Because their jokes always had a \"magical\" twist!");
        baldursGateJokes.add("What do you call a tavern brawl in Baldur's Gate? A \"melee\"!");
        baldursGateJokes.add("Why did the rogue in Baldur's Gate start a locksmith business? Because they could \"pick\" the best opportunities!");
        baldursGateJokes.add("What's a fighter's favorite bedtime story in Baldur's Gate? \"The Tale of the Critical Hit\"!");
        baldursGateJokes.add("Why did the warlock in Baldur's Gate become a motivational speaker? Because they could \"charm\" any audience!");
        baldursGateJokes.add("What's a druid's favorite sport in Baldur's Gate? \"Tree-kicking\"!");
        baldursGateJokes.add("Why did the gnome in Baldur's Gate start a fireworks shop? Because they loved to \"spark\" excitement!");
        baldursGateJokes.add("How do you become the mayor of Baldur's Gate? Win the \"campaign\"!");
        baldursGateJokes.add("Why did the bard in Baldur's Gate become a sailor? Because they wanted to \"sea\" the world!");
        baldursGateJokes.add("Why did the thief in Baldur's Gate open a bakery? Because they wanted to steal the \"dough\"!");
        baldursGateJokes.add("What's a mage's favorite holiday in Baldur's Gate? \"Fireworks Day\"!");
        baldursGateJokes.add("Why did the cleric in Baldur's Gate start a gardening club? Because they believed in \"divine growth\"!");
        baldursGateJokes.add("How do you spot a tourist in Baldur's Gate? They're the ones asking for directions to the \"Baldur's Gate\"!");
        baldursGateJokes.add("What's a paladin's favorite board game in Baldur's Gate? \"Holy Chess\"!");
        baldursGateJokes.add("Why did the ranger in Baldur's Gate become a wildlife photographer? Because they wanted to capture the \"wildlife\"!");
        baldursGateJokes.add("What do you call a tavern with no bards in Baldur's Gate? A \"silent night\"!");
        baldursGateJokes.add("Why did the dwarf in Baldur's Gate open a mining company? Because they knew the \"ore-ders\" would come!");
        baldursGateJokes.add("What's a sorcerer's favorite TV show in Baldur's Gate? \"Spellbound Spectacles\"!");
        baldursGateJokes.add("Why did the fighter in Baldur's Gate enroll in cooking school? Because they wanted to master the \"sword-ine\" arts!");
        baldursGateJokes.add("What's a rogue's favorite subject in school in Baldur's Gate? \"Stealth Studies\"!");
        baldursGateJokes.add("Why did the druid in Baldur's Gate join a music band? Because they could \"harmonize\" with nature!");
        baldursGateJokes.add("What's a warlock's favorite instrument in Baldur's Gate? The \"eldritch guitar\"!");
        baldursGateJokes.add("Why did the gnome in Baldur's Gate become an inventor? Because they loved to create \"gnome-chucks\"!");
        baldursGateJokes.add("What's a bard's favorite type of cheese in Baldur's Gate? \"Bard-onzola\"!");
        baldursGateJokes.add("Why did the wizard in Baldur's Gate become a librarian? Because they wanted to \"book\" their future!");
        baldursGateJokes.add("What do you call a group of wizards in Baldur's Gate? A \"spell-caster\"!");
        baldursGateJokes.add("Why did the halfling in Baldur's Gate become a detective? Because they could \"uncover\" any mystery!");
        baldursGateJokes.add("What's a cleric's favorite game in Baldur's Gate? \"Divine Intervention\"!");
        baldursGateJokes.add("Why did the sorcerer in Baldur's Gate become a weather forecaster? Because they could predict \"spell-showers\"!");
        jokesByCategory.put("BaldursGate", baldursGateJokes);

        //Dad Jokes
        List<String> dadJokes = new ArrayList<>();
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("I told my wife she was drawing her eyebrows too high. She looked surprised.");
        dadJokes.add("Did you hear about the kidnapping at the park? They woke up!");
        dadJokes.add("I couldn't figure out how to put my seatbelt on. Then it clicked!");
        dadJokes.add("What's brown and sticky? A stick!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why don't scientists trust atoms? Because they make up everything!");
        dadJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("Why don't skeletons fight each other? They don't have the guts!");
        dadJokes.add("How do you organize a space party? You planet!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What's brown and sticky? A stick!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What do you call a fish with no eyes? Fsh!");
        dadJokes.add("How do you make a tissue dance? You put a little boogie in it!");
        dadJokes.add("What's orange and sounds like a parrot? A carrot!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why don't scientists trust atoms? Because they make up everything!");
        dadJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("Why don't skeletons fight each other? They don't have the guts!");
        dadJokes.add("How do you organize a space party? You planet!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What's brown and sticky? A stick!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What do you call a fish with no eyes? Fsh!");
        dadJokes.add("How do you make a tissue dance? You put a little boogie in it!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why don't scientists trust atoms? Because they make up everything!");
        dadJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("Why don't skeletons fight each other? They don't have the guts!");
        dadJokes.add("How do you organize a space party? You planet!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What's brown and sticky? A stick!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What do you call a fish with no eyes? Fsh!");
        dadJokes.add("How do you make a tissue dance? You put a little boogie in it!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why don't scientists trust atoms? Because they make up everything!");
        dadJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("Why don't skeletons fight each other? They don't have the guts!");
        dadJokes.add("How do you organize a space party? You planet!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What's brown and sticky? A stick!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why did the scarecrow win an award? Because he was outstanding in his field!");
        dadJokes.add("What do you call a fish with no eyes? Fsh!");
        dadJokes.add("How do you make a tissue dance? You put a little boogie in it!");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("Why don't scientists trust atoms? Because they make up everything!");
        dadJokes.add("Parallel lines have so much in common. It’s a shame they’ll never meet.");
        dadJokes.add("I'm reading a book on anti-gravity. It's impossible to put down!");
        dadJokes.add("I used to play piano by ear, but now I use my hands.");
        dadJokes.add("Why don't skeletons fight each other? They don't have the guts!");
        dadJokes.add("How do you organize a space party? You planet!");
        jokesByCategory.put("Dad", dadJokes);
// Add more dad jokes here

    }

    public static String getRandomJoke(String category) {
        List<String> jokes;
        if (category == null || category.isEmpty() || !jokesByCategory.containsKey(category)) {
            // If category is not specified or not found, pick a random category
            List<String> categories = new ArrayList<>(jokesByCategory.keySet());
            String randomCategory = categories.get(random.nextInt(categories.size()));
            jokes = jokesByCategory.get(randomCategory);
        } else {
            jokes = jokesByCategory.get(category);
        }

        return jokes.get(random.nextInt(jokes.size()));
    }
}
